Optimize resolving deps and support x86 old aria2

diff --git a/cyg-fast b/cyg-fast
--- a/cyg-fast
+++ b/cyg-fast
@@ -34,8 +34,6 @@ type aria2c tar gawk &> /dev/null || {
   exit 1
 }
 
-ARIA2C=( "aria2c" "--conditional-get" "--allow-overwrite" )
-
 function usage()
 {
   echo cyg-fast: Installs and removes Cygwin packages.
@@ -67,8 +65,6 @@ function usage()
   echo "  --version"
 }
 
-
-
 function version()
 {
   echo "cyg-fast version 0.57"
@@ -81,6 +77,14 @@ function current_cygarch ()
 {
   arch | sed -e 's/^i686$/x86/g'
 }
+
+if [ `current_cygarch` = "x86" ]; then
+  echo "Warning: x86 env detected: aria2 can't use --conditional-get, always download and overwrite"
+  ARIA2C=( "aria2c" "--allow-overwrite=true" )
+else
+  ARIA2C=( "aria2c" "--conditional-get" "--allow-overwrite" )
+fi
+
 
 function mirror_to_mirrordir ()
 {
@@ -544,6 +548,8 @@ function cyg-fast-install ()
 
 function resolve_deps()
 {
+    while true ; do
+
     echo -n "."
     pkgs=${CURRENT[@]}
     CURRENT=""
@@ -572,7 +578,7 @@ function resolve_deps()
           exit 1
         fi
       else
-        [ -f release/$pkg/desc ] || {
+        [ -f release/$pkg/desc -a `echo release/$pkg/desc` != "Package not found" ] || {
           echo; echo Package $pkg not found or ambiguous name, exiting
           rm /tmp/cyg-fast-* 2> /dev/null
           exit 1
@@ -592,6 +598,7 @@ function resolve_deps()
 
       local requires=""
 
+
       if [ -d deptree ]; then
         requires=`cat deptree/$pkg/requires`
       else
@@ -605,12 +612,9 @@ function resolve_deps()
           local already="$(grep -c "$package " /etc/setup/installed.db)" 
           if [ $already = 0 ]; then
             CURRENT=( ${CURRENT[@]} $package )
-            if [ $? -ne 0 ]; then warn=1; fi
           fi
         done
       fi
-
-      [ $warn = 0 ] || echo "Warning: some required packages do not install, continuing"
 
       if [ -z "$install" ]; then
         echo "Could not find \"install\" in package description: obsolete package?"
@@ -621,7 +625,8 @@ function resolve_deps()
     
     # tailcall
 
-    [ $hasdeps = 0 ] ||  resolve_deps;
+    [ $hasdeps = 0 ] && break;
+    done
 }
 
 function cyg-fast-resume-install()
@@ -643,9 +648,9 @@ function cyg-fast-resume-install()
     # download all
     
     echo "Start downloading..."
-    ${ARIA2C[@]} --deferred-input \
-                 --input-file /tmp/cyg-fast-downloads \
-                 -x $maxcount || {
+    ${ARIA2C[@]} --input-file /tmp/cyg-fast-downloads \
+                 `[ $(current_cygarch) = "x86" ] || echo "--deferred-input"` \
+                 -j $maxcount || {
       echo "Interrupted: To resume installing, run \"cyg-fast resume-install\" ."
       exit 1
     }
